#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/Users/monucarpenter/C++/codeforces/node_modules/.pnpm/nodeforces@1.0.0/node_modules/nodeforces/bin/node_modules:/Users/monucarpenter/C++/codeforces/node_modules/.pnpm/nodeforces@1.0.0/node_modules/nodeforces/node_modules:/Users/monucarpenter/C++/codeforces/node_modules/.pnpm/nodeforces@1.0.0/node_modules:/Users/monucarpenter/C++/codeforces/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/Users/monucarpenter/C++/codeforces/node_modules/.pnpm/nodeforces@1.0.0/node_modules/nodeforces/bin/node_modules:/Users/monucarpenter/C++/codeforces/node_modules/.pnpm/nodeforces@1.0.0/node_modules/nodeforces/node_modules:/Users/monucarpenter/C++/codeforces/node_modules/.pnpm/nodeforces@1.0.0/node_modules:/Users/monucarpenter/C++/codeforces/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../bin/nodeforces" "$@"
else
  exec node  "$basedir/../../bin/nodeforces" "$@"
fi
